<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>3.0.0</Version>
    <PackageProjectUrl>https://github.com/LazyCoderSuhe/SH.DbRepository/tree/master</PackageProjectUrl>
  </PropertyGroup>



  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
  </ItemGroup>

</Project>
